apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      securityContext:
        runAsGroup: 100 # writable directories are accessible with GID 100. see https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile
      containers:
      - name: jupyter
        image: jupyter/minimal-notebook
        command: ["jupyter-lab"]
        args: ["--ip='*'", "--NotebookApp.token=''", "--NotebookApp.password=''"]
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        resources:
          requests:
            memory: 1G
            cpu: 1
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter
spec:
  ports:
  - name: http
    port: 8888
  selector:
    app: jupyter
